language: c

os:
    - linux

sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:

        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - EVENT_TYPE='pull_request push'

        - CONDA_ENVIRONMENT='environment.yml'
        - CONDA_DEPENDENCIES='jupyter ipython'
        - CONDA_CHANNELS='astropy-ci-extras astropy'

        # We need to install the master/latest version of nbconvert because it has support for
        # allowing exceptions in individual cells:
        - PIP_DEPENDENCIES='git+https://github.com/jupyter/nbconvert junit_xml'

# matrix:

#     # Don't wait for allowed failures
#     fast_finish: true

#     include:

#         - os: linux
#           env: SETUP_CMD='test --coverage'

install:

    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   # - |
   #   python scripts/convert.py docs/_static/tutorials/ -v
   #   --output-path=docs/rst-tutorials
   #   --template=docs/_static/astropy.tpl
   - python scripts/convert.py tutorials/notebooks --exec-only -v
