name: notebooks_env

# add conda channels to search for packages here
channels:
  - astropy
  - astropy-ci-extras
  - http://ssb.stsci.edu/astroconda
  - defaults

# add conda dependencies here
dependencies:
  - numpy=1.15.4
  - astropy
  - scipy
  - astroquery
  - matplotlib
  - jupyter
  - pandas
  - drizzlepac
  - crds
  - ccdproc
  - acstools
  - photutils
  - regions
  - pyregion
# add pip dependencies here
  - pip:
    - k2flix
    - git+https://github.com/eteq/nbpages.git
